const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger.json'
const endpointsFiles = ['./routes/user.routes', './routes/employee.routes']
const doc = {
  info: {
    version: "1.0.0",
    title: "Equipment Distribution System API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:2000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
    },
  },
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./app.js')
})